# app配置
app:
  # 协议
  protocol:   funtask
  # 系统托盘配置
  tray:
    # 是否显示
    visible:  true
    # 托盘图标
    icon:     ''

# 开发环境配置
dev:
  # 调试的插件目录
  debugdirs:
    - F:\work\suwis\longTimeProject\youdao
    - F:\work\suwis\longTimeProject\youdao1
    - F:\work\suwis\longTimeProject\youdao2
    - F:\work\suwis\longTimeProject\youdao3
    - F:\work\suwis\longTimeProject\youdao4
    - F:\work\suwis\longTimeProject\youdao5
    - F:\work\suwis\longTimeProject\youdao6
    - F:\work\suwis\longTimeProject\youdao7
    - F:\work\suwis\longTimeProject\youdao8
    - F:\work\suwis\longTimeProject\youdao9
    - E:\work\suwis\LongRunProject\youdao
    - E:\work\suwis\LongRunProject\youdao1
    - E:\work\suwis\LongRunProject\youdao2
    - E:\work\suwis\LongRunProject\youdao3
    - E:\work\suwis\LongRunProject\youdao4
    - E:\work\suwis\LongRunProject\youdao5
    - E:\work\suwis\LongRunProject\youdao6
    - E:\work\suwis\LongRunProject\youdao7
    - E:\work\suwis\LongRunProject\youdao8
    - E:\work\suwis\LongRunProject\youdao9
