# app配置
app:
  # 系统托盘配置
  tray:
    # 是否显示
    visible:  true
    # 托盘图标
    icon:     ''

# 开发环境配置
dev:
  # 调试的插件目录
  debugdirs:
    - F:\work\suwis\longTimeProject\funtask_youdao
    - F:\work\suwis\longTimeProject\funtask_youdao1
    - F:\work\suwis\longTimeProject\funtask_youdao2
    - F:\work\suwis\longTimeProject\funtask_youdao3
    - F:\work\suwis\longTimeProject\funtask_youdao4
    - F:\work\suwis\longTimeProject\funtask_youdao5
    - F:\work\suwis\longTimeProject\funtask_youdao6
    - F:\work\suwis\longTimeProject\funtask_youdao7
    - F:\work\suwis\longTimeProject\funtask_youdao8
    - F:\work\suwis\longTimeProject\funtask_youdao9
