# app配置
app:
  # 协议
  protocol:       funtask
  # 自动启动
  autostart:      false
  # 仓库地址
  registrys:
    - https://npm.suwis.com

  # 系统托盘配置
  tray:
    # 是否显示
    visible:      true
    # 托盘图标
    icon:         ''
  # 通知
  notice:
    # 显示停留时间
    delay:        5000
  # 悬浮球
  window:
    alwaysOnTop:  true

# 开发环境配置
dev:
  # 调试的插件目录
  debugdirs:
