# app配置
app:
  # 协议
  protocol:   funtask
  # 系统托盘配置
  tray:
    # 是否显示
    visible:  true
    # 托盘图标
    icon:     ''
  # 通知
  notice:
    # 显示停留时间
    delay:    5000

# 开发环境配置
dev:
  # 调试的插件目录
  debugdirs:
